Assets/Scripts/Attack.cs, Assets/Scripts/AttackController.cs
命中率について実装しました.
レビューの方をよろしくお願いします.
close #6
=> [feat] Accuracy Implemented.

Assets/Scripts/BoardController.cs
戦闘のフェーズを確認するためのenumを作りました。
Stateパターンは適用できなさそうなのでenumです。
移動や攻撃は、ユーザーがFloor/Unitをクリックすることで実行されますが、
その時に、現在の戦闘状態が無い場合は、
関数間の口約束のみで移動→コマンド選択に移行しバグが出やすいので作ってます。
=> 19 state property

Assets/Scripts/AI.cs, Assets/Scripts/Attacks/SingleAttack.cs, Assets/Scripts/Map.cs
close #1 
攻撃範囲の解消, #17 に付随して解決しました.
=> [Add] Refactor the attack Range.

Assets/Scripts/Unit.cs
ユニットの攻撃に関する状態を管理するためのEnum型を作りました。
目的は、
- 実行可能な攻撃コマンドのLINQ.where();
- 強攻撃溜め/強攻撃に対する特殊制御構造
には必要不可欠な情報だからです。
微妙に怪しい所はEnum,property名が似ていることなので、そこで案があったら教えて下さい。
具体的な役割詳細は、以下の通りです。
=> [Add] #20 AttackStates & AttackState

Assets/Scripts/AttackController.cs, Assets/Scripts/BoardController.cs, Assets/Scripts/DamageCalculator.cs, Assets/Scripts/Floor.cs, Assets/Scripts/Type.cs, Assets/Scripts/Unit.cs
移動後の移動量を減らす操作が実装されていなかったため, 仕様を満たして正常に移動することを確認しました.
__マージする際にはpremasterである #41 にマージするようお願いします.__
__premasterとのDiffに関しては,
https://github.com/at0x0ft/SRPG2018/pull/44/commits/e60806e552918303323d584fe241c87e92e255e1
を参考にしてください.__
このうち, premasterへのマージする前に,
// 4debugで書かれた部分に関しては消す方が良いかなぁなんて思っております.
(UnityのDebugコンソールが見にくくなるので)
=> [fix] Move amount update fix

.gitignore, Assets/Scripts/Unit.cs
移動時にユニットをクリックすると「移動しない」を実行できるようにしました
Close #53
=> fix: zero moving

Assets/Scenes/Test.unity, Assets/Scripts/AI.cs, Assets/Scripts/BoardController.cs, Assets/Scripts/Map.cs, Assets/Scripts/SubWindows/AttackSelectWindow.cs, Assets/Scripts/SubWindows/RangeAttackNozzle.cs
=> [feat]14 implement ai

Assets/Scenes/Test.unity, Assets/Scripts/SubWindows/RangeAttackNozzle.cs
範囲攻撃ボタンを、範囲攻撃時以外は非表示になるようにします。
close 62
=> [feat]62 hide range attack nozzle on non attacking

Assets/Resources/Prefabs/DamagePopUp.prefab, Assets/Resources/Prefabs/DamagePopUp.prefab.meta, Assets/Scenes/Test.unity, Assets/Scripts/SubWindows/DamagePopUp.cs, Assets/Scripts/SubWindows/DamagePopUp.cs.meta, Assets/Scripts/UI.cs, Assets/Scripts/Unit.cs
ダメージを受けたときに、その量をユニットの上空に表示するシステムを作りました。
簡易的なので、必要に応じてDamagePopUp.csやDamagePopUp.prefabの変数などを書き換えてください。
close #61
=> [feat]61 display damage popup

Assets/Scripts/AttackController.cs, Assets/Scripts/BattleStateController.cs, Assets/Scripts/BoardController.cs, Assets/Scripts/Floor.cs, Assets/Scripts/Map.cs, Assets/Scripts/MoveController.cs, Assets/Scripts/Unit.cs
* UnitInfoWindowとMoveAmountInfoWindowのデフォルト表示をActiveUnitにしました
* IsMovedと不要な処理を削除しました
Close #63
=> [feat] default unit info

Assets/Scripts/BoardController.cs
敵の行動を妨害出来ちゃうのは、touchblockerの動作が上手くいってなかっただったので、修正しました。
close #68
=> [Fix] enable touch blocker more sensitivity & fix ai information

Assets/Scenes/Test.unity, Assets/Scripts/Attacks/SingleAttack.cs, Assets/Scripts/BattleStateController.cs, Assets/Scripts/SubWindows/AttackSelectWindow.cs, Assets/Scripts/SubWindows/RangeAttackNozzle.cs, Assets/Scripts/Unit.cs
強攻撃について仕様変更を適用しました
（強攻撃は、Set1のときにChargeボタンを押して待機して、Set2のときに攻撃をする）。
多分SceneFileの差分は全然ないので、merge出来ます。
close #84
=> [feat]84 change request strong attack

Assets/Resources/Prefabs/Units/suisei.prefab, Assets/Scenes/Test.unity, Assets/Scripts/BoardController.cs, Assets/Scripts/GameEndPanel.cs, Assets/Scripts/GameEndPanel.cs.meta, Assets/Scripts/HpBar.cs, Assets/Scripts/UI.cs
ゲーム終了画面を実装しました.
(レビュー待ってられないので即マージしてしまいます...)
close #100
=> [feat] Implement Game Ending

Assets/Scripts/AttackController.cs, Assets/Scripts/DamageCalculator.cs, Assets/Scripts/PopUp/PopUpController.cs, Assets/Scripts/Unit.cs
めっちゃシンプルだったので実装しました。
攻撃が失敗したら、ダメージが「miss」と表示され、
強攻撃解除が行われなくなりました。
close #112
=> [feat] missing attack

Assets/Resources/Prefabs/StrongEffectFactory.prefab, Assets/Resources/Prefabs/StrongEffectFactory.prefab.meta, Assets/Scenes/Test.unity, Assets/Scripts/AttackController.cs, Assets/Scripts/ChargeEffectController.cs, Assets/Scripts/ChargeEffectController.cs.meta, Assets/Scripts/SubWindows/RangeAttackNozzle.cs, Assets/Scripts/UI.cs, Assets/Scripts/Unit.cs
強攻撃溜めの時や、範囲攻撃ボタンなどに対して、光らせるようにしました。
マージするときは、Sceneファイルが難しそうだったら、prefab化してあるので、
StrongEffectFactory.prefabをHierarchyにぶち込んでください。
close #115
=> [feat]115 super cyer effect

Assets/Resources/Prefabs/Types/Dark.prefab, Assets/Resources/Prefabs/Types/Fire.prefab, Assets/Resources/Prefabs/Types/Light.prefab, Assets/Resources/Prefabs/Types/Rock.prefab, Assets/Resources/Prefabs/Types/Water.prefab, Assets/Resources/Prefabs/Types/Wind.prefab, Assets/Resources/Prefabs/Units/suisei.prefab, Assets/Scenes/Test.unity, Assets/Scripts/BoardController.cs, Assets/Scripts/DamageCalculator.cs, Assets/Scripts/Floor.cs, Assets/Scripts/MoveController.cs, Assets/Scripts/SubWindows/AttackInfoWindow.cs, Assets/Scripts/SubWindows/FloorInfoWindow.cs, Assets/Scripts/SubWindows/RangeAttackNozzle.cs, Assets/Scripts/SubWindows/TurnSetInfoWindow.cs, Assets/Scripts/SubWindows/UnitInfoWindow.cs, Assets/Scripts/Type.cs
UIを日本語化し, ウィンドウサイズを再調整しました.
close #119
=> [feat] UI Localizing

Assets/Scripts/AI.cs, Assets/Scripts/BoardController.cs, Assets/Scripts/Unit.cs, Assets/Scripts/Units.cs
ターンプレイヤーの持つキャラクター一覧の順番を整理するメソッドを, 実装しました.
これに伴って, ゲーム開始時の処理のメソッド等の整理, リネームや, ゲーム勝利/敗北関連のメソッドもある程度整えました. (ゲーム終了処理に関しては, #15 で行うため, ブランクコードのみ書いておきました.)
レビューお願いします.
close #28
=> [feat] Implement character order

Assets/ButtonTest.cs, Assets/Scripts/AI.cs, Assets/Scripts/AttackController.cs, Assets/Scripts/BoardController.cs, Assets/Scripts/ButtonRejudge.cs, Assets/Scripts/ChargeEffectController.cs, Assets/Scripts/Map.cs, Assets/Scripts/PopUp/BasePopUp.cs, Assets/Scripts/PopUp/DamagePopUp.cs, Assets/Scripts/SubWindows/AttackSelectWindow.cs, Assets/Scripts/SubWindows/RangeAttackNozzle.cs, Assets/Scripts/Unit.cs, Assets/Scripts/Units.cs
敵が攻撃しないバグの修正です。
何故かMap.csにおいて、マップのX,Y座標の最大値を取得するところで、
謎の処理が追記されていた結果、正常に最大値が取れていませんでした。
削除したら攻撃が再開しました。
一部Enemyの攻撃時に例外処理が含まれていなかったため、作成中です
close #128
=> [feat] enemy can't attack

Assets/Scripts/MoveController.cs, Assets/Scripts/Unit.cs
移動コストが正常に計算されていないバグを直しました.
close #137
=> [Fixed] Correct cost decrease.

Assets/Scenes/Test.unity, Assets/Scripts/Attacks/Attack.cs, Assets/Scripts/SubWindows/AttackInfoWindow.cs
"必中"と表記されるよう, 修正しました.
サブウィンドウのレイアウトを変更したので, もしよろしければ確認してください.
close #145
=> [feat] Implemented view of "necessarily hit".

Assets/Scenes/Chapter4.meta, Assets/Scenes/Chapter4/Chapter4After.unity, Assets/Scenes/Chapter4/Chapter4After.unity.meta, Assets/Scenes/Chapter4/Chapter4Before.unity, Assets/Scenes/Chapter4/Chapter4Before.unity.meta
内容が分かるぐらいのシーンにはなりました。
あとはChapter3と同様の作業＋
フローチャート、ゲームオブジェクト整形ぐらいです。
=> 148 scenario task chapter4

Assets/Scenes/Chapter6.meta, Assets/Scenes/Chapter6/Chapter6After.unity, Assets/Scenes/Chapter6/Chapter6After.unity.meta, Assets/Scenes/Chapter6/Chapter6Before.unity, Assets/Scenes/Chapter6/Chapter6Before.unity.meta
名前と流れは合ってる。
効果音のところは後で追加実装する。
どうしてもConversationで表示されない画像は
Portraitで対処した。
close #150
=> 150 scenario task chapter6

Assets/Scenes/Chapter7.meta, Assets/Scenes/Chapter7/Chapter7After.unity, Assets/Scenes/Chapter7/Chapter7After.unity.meta, Assets/Scenes/Chapter7/Chapter7Before.unity, Assets/Scenes/Chapter7/Chapter7Before.unity.meta
=> 151 scenario task chapter7

Assets/Scenes/Chapter8.meta, Assets/Scenes/Chapter8/Chapter8After.unity, Assets/Scenes/Chapter8/Chapter8After.unity.meta, Assets/Scenes/Chapter8/Chapter8Before.unity, Assets/Scenes/Chapter8/Chapter8Before.unity.meta
ちょっと長いけど、
キャラ対応合ってるか
時間あれば確認してください。
close #152
=> 152 scenario task chapter8

Assets/Scenes/Chapter9.meta, Assets/Scenes/Chapter9/Chapter9After.unity, Assets/Scenes/Chapter9/Chapter9After.unity.meta, Assets/Scenes/Chapter9/Chapter9Before.unity, Assets/Scenes/Chapter9/Chapter9Before.unity.meta
シナリオテキスト終了。
今後私のやることは、
・人物、背景画像差し替え（一番大変）
・音声、BGMの挿入
・テキスト表示の改変（強調や色づけとかも多分できる）
とかになるのかな。
close #153
=> 153 scenario task chapter9

Assets/Scripts/AI.cs, Assets/Scripts/Accessories/ChargeEffectController.cs, Assets/Scripts/Floor.cs, Assets/Scripts/Moderator/BattleStateController.cs, Assets/Scripts/Moderator/BoardController.cs, Assets/Scripts/MoveController.cs, Assets/Scripts/PopUp/AttackEffect.cs, Assets/Scripts/SubWindows/AttackSelectWindow.cs
Fixed
- 現在位置の誤認識バグ（related to 攻撃出来るのにしないバグ、移動先が被るバグ）
- エリア上端に居るユニットを攻撃しないバグ
- 攻撃出来る敵がいるにもかかわらず、攻撃相手一覧に存在せず配列外参照となるバグ
- 1度の攻撃コマンドクリックで30回以上クリックした内部判定になっているバグ
- 実行中のFungus Blockを再実行してしまい、警告が大量に出てしまうバグ
BigChanged
- 移動モーション中は、攻撃コマンドが表示されず、行動終了ボタンも押せません（押せるとバグるため）
~~配列外参照バグについては、恐らくは治っていると思われるものの、
治っていることの確認手法が無い（エラーが発生しない）ため、
今後のテストプレーで問題が出たら直すくらいの認識になりそう。
（プレイヤーの行動終了連打では、5回連続で問題なし）~~
意図的にバグが起こりうる状況を発生させ、かつ発生を検知するシステムを構築。
結果、バグの対処が達成出来ていることを確認。
close #175
=> [feat] 175 ai bugfix

Assets/Scenes/Chapter2/Chapter2After.unity, Assets/Scenes/Chapter2/Chapter2Before.unity
ここも素材がそろっている(Daily.midを除く)
特に問題なければほぼ完成です。
突然曲が止まってラスボスっぽいBGMに切り替わるのが
最高に面白かったです。
ただ、あまり前触れなしに
曲をコロコロ変えるのは
ユーザーをイラっとさせるので
ほどほどにした方がいいですね。
close #176
=> [WIP]insert bgm and background in chapter2

Assets/Scenes/Chapter1/Chapter1Before.unity, Assets/Scenes/Chapter3/Chapter3After.unity, Assets/Scenes/Chapter3/Chapter3Before.unity
=> [WIP]insert bgm and background in chapter3

Assets/Scenes/Chapter5/Chapter5After.unity, Assets/Scenes/Chapter5/Chapter5Before.unity
機能が増えてるから
コミットメッセージにはfeatって書いてあるけど、
実際立ち絵がそろってないので[WIP]です。
=> [WIP] insert bgm and background in chapter5

Assets/Scenes/Chapter6/Chapter6After.unity, Assets/Scenes/Chapter6/Chapter6Before.unity
Afterの方なんですが、
ちょっと音声に切り替わりが多い気がするので、
そこは聞いて確かめてもらいたいです。
=> [WIP]insert bgm and background in chapter6

Assets/Resources/Prefabs/Buttons.prefab, Assets/Scenes/Chapter1/Chapter1Battle.unity, Assets/Scripts/AI.cs, Assets/Scripts/Moderator/GameEndPanel.cs, Assets/Scripts/SubWindows/AttackSelectWindow.cs
戦闘場面終了後の遷移システムをとりあえず実装します。
その後多分、chapter間の全ての連結を実装するかもです。
close #201
=> [WIP]Scene merge

Assets/Resources/Prefabs/FungusFlowchartSystem.prefab, Assets/Resources/Prefabs/TeamInfoWindow.prefab, Assets/Resources/Prefabs/TeamInfoWindow.prefab.meta, Assets/Scenes/Chapter1/Chapter1Battle.unity, Assets/Scripts/Accessories/HpBar.cs, Assets/Scripts/Floor.cs, Assets/Scripts/Moderator/BoardController.cs, Assets/Scripts/SubWindows/FloorInfoWindow.cs, Assets/Scripts/SubWindows/TeamInfoWindow.cs, Assets/Scripts/SubWindows/TeamInfoWindow.cs.meta, Assets/Scripts/UI.cs, Assets/Scripts/Unit.cs
あたふたが実装断念したっぽいので、実装してみました。
TeamInfoWindowを他のシーンに追加したら動くようにしたつもり。
ただ、エラー文と被るからそこら辺を修正中。
=> [feat]top hp bar

Assets/Scripts/SubWindows/AttackSelectWindow.cs
画面上部に攻撃を表示するのは難しいですが、
選択した攻撃をピンク色にすることは出来ました。
close #87
=> [feat] selected button is pink
